version: '3'

vars:
  UE_PATH: "C:\\Games\\UE_5.6"
  PROJECT_PATH: "C:\\Users\\NGamezz\\Documents\\UnrealProjects\\NapTime5.6\\Nap_Time.uproject"
  OUTPUT_PATH: "C:\\Games\\UE_Output"

# $env:UE_PATH\Engine\Build\BatchFiles\RunUAT.bat BuildCookRun -project="$env:PROJECT_PATH" -noP4 -platform=Win64 -clientconfig=Development -serverconfig=Development -cook -allmaps -build -stage -pak -archive -archivedirectory="$env:OUTPUT_PATH"
tasks:
  default:
    preconditions:
      - cargo version
    cmds:
      - cargo build -r
      - Powershell.exe mv "target//release//ci_helper.exe" . 
      - echo "{{.GREETING}}"
    silent: true

  build_ue:
    cmds:
      - Powershell.exe "{{.UE_PATH}}\\Engine\\Build\\BatchFiles\\RunUAT.bat BuildCookRun -project={{.PROJECT_PATH}} -noP4 -platform=Win64 -clientconfig=Development -serverconfig=Development -cook -allmaps -build -stage -pak -archive -archivedirectory={{.OUTPUT_PATH}}"
